# Generated by Django 6.0.6 on 2026-07-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('openrouter', 'OpenRouter'), ('nvidia', 'Nvidia NIM')], default='openai', max_length=50)),
                ('model_name', models.CharField(blank=True, help_text='e.g., gpt-4o or claude-3-5-sonnet-20240620. Leave blank for default.', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one configuration can be active at a time.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Provider Configuration',
                'verbose_name_plural': 'AI Provider Configurations',
            },
        ),
    ]
