# Generated by Django 6.0.6 on 2026-07-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproviderconfig',
            name='api_key',
            field=models.CharField(blank=True, help_text='If provided, this overrides the environment variable API key.', max_length=255, null=True),
        ),
    ]
