# Generated by Django 6.0.6 on 2026-07-05 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_aiproviderconfig_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=200, verbose_name='Model ID')),
                ('display_name', models.CharField(blank=True, max_length=200, verbose_name='Display Name')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Model',
                'verbose_name_plural': 'AI Models',
                'ordering': ['model_id'],
            },
        ),
        migrations.CreateModel(
            name='AIProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('openrouter', 'OpenRouter'), ('nvidia', 'Nvidia NIM')], max_length=50, unique=True, verbose_name='Provider')),
                ('api_key', models.CharField(blank=True, max_length=512, null=True, verbose_name='API Key')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Provider',
                'verbose_name_plural': 'AI Providers',
                'ordering': ['provider_name'],
            },
        ),
        migrations.DeleteModel(
            name='AIProviderConfig',
        ),
        migrations.AddField(
            model_name='aimodel',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='ai.aiprovider'),
        ),
        migrations.AlterUniqueTogether(
            name='aimodel',
            unique_together={('provider', 'model_id')},
        ),
    ]
