# Generated by Django 6.0.6 on 2026-07-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_aimodel_aiprovider_delete_aiproviderconfig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprovider',
            name='provider_name',
            field=models.CharField(choices=[('groqcloud', 'GroqCloud'), ('gemini', 'Google Gemini'), ('openrouter', 'OpenRouter'), ('nvidia', 'Nvidia NIM')], max_length=50, unique=True, verbose_name='Provider'),
        ),
    ]
