# Generated by Django 6.0.6 on 2026-07-10 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_options_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(blank=True, default='', help_text='Free-text context facts about the user (preferences, bio, etc.)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User this memory belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='memory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Memory',
                'verbose_name_plural': 'User Memories',
                'db_table': 'accounts_usermemory',
            },
        ),
    ]
