# Generated by Django 6.0.6 on 2026-07-25 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
            ],
            options={
                'verbose_name': 'AI Chat Conversation',
                'verbose_name_plural': 'AI Chat Conversations',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chat.conversation',),
        ),
        migrations.CreateModel(
            name='SEAConversation',
            fields=[
            ],
            options={
                'verbose_name': 'SEA Task',
                'verbose_name_plural': 'SEA Tasks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('chat.conversation',),
        ),
    ]
